"""Public enums. FlightDataType and FlightEvent are generated by
tools/generate_enums.py as the union of constants across all version profiles;
availability on the loaded OpenRocket version is enforced when translating.
Do not edit them by hand — regenerate instead."""

from enum import Enum, auto

__all__ = [
    "OrLogLevel",
    "FlightDataType",
    "FlightEvent",
]


class OrLogLevel(Enum):
    OFF = auto()
    ERROR = auto()
    WARN = auto()
    INFO = auto()
    DEBUG = auto()
    TRACE = auto()
    ALL = auto()


class FlightDataType(Enum):
    TYPE_ACCELERATION_TOTAL = auto()
    TYPE_ACCELERATION_XY = auto()
    TYPE_ACCELERATION_Z = auto()
    TYPE_AIR_DENSITY = auto()
    TYPE_AIR_PRESSURE = auto()
    TYPE_AIR_TEMPERATURE = auto()
    TYPE_ALTITUDE = auto()
    TYPE_ALTITUDE_ABOVE_SEA = auto()
    TYPE_AOA = auto()
    TYPE_AXIAL_DRAG_COEFF = auto()
    TYPE_BASE_DRAG_COEFF = auto()
    TYPE_CG_LOCATION = auto()
    TYPE_COMPUTATION_TIME = auto()
    TYPE_CORIOLIS_ACCELERATION = auto()
    TYPE_CP_LOCATION = auto()
    TYPE_DRAG_COEFF = auto()
    TYPE_DRAG_FORCE = auto()
    TYPE_FRICTION_DRAG_COEFF = auto()
    TYPE_GRAVITY = auto()
    TYPE_LATITUDE = auto()
    TYPE_LONGITUDE = auto()
    TYPE_LONGITUDINAL_INERTIA = auto()
    TYPE_MACH_NUMBER = auto()
    TYPE_MASS = auto()
    TYPE_MOTOR_MASS = auto()
    TYPE_NORMAL_FORCE_COEFF = auto()
    TYPE_ORIENTATION_PHI = auto()
    TYPE_ORIENTATION_THETA = auto()
    TYPE_PITCH_DAMPING_MOMENT_COEFF = auto()
    TYPE_PITCH_MOMENT_COEFF = auto()
    TYPE_PITCH_RATE = auto()
    TYPE_POSITION_DIRECTION = auto()
    TYPE_POSITION_X = auto()
    TYPE_POSITION_XY = auto()
    TYPE_POSITION_Y = auto()
    TYPE_PRESSURE_DRAG_COEFF = auto()
    TYPE_PROPELLANT_MASS = auto()
    TYPE_REFERENCE_AREA = auto()
    TYPE_REFERENCE_LENGTH = auto()
    TYPE_REYNOLDS_NUMBER = auto()
    TYPE_ROLL_DAMPING_COEFF = auto()
    TYPE_ROLL_FORCING_COEFF = auto()
    TYPE_ROLL_MOMENT_COEFF = auto()
    TYPE_ROLL_RATE = auto()
    TYPE_ROTATIONAL_INERTIA = auto()
    TYPE_SIDE_FORCE_COEFF = auto()
    TYPE_SPEED_OF_SOUND = auto()
    TYPE_STABILITY = auto()
    TYPE_THRUST_FORCE = auto()
    TYPE_THRUST_WEIGHT_RATIO = auto()
    TYPE_TIME = auto()
    TYPE_TIME_STEP = auto()
    TYPE_VELOCITY_TOTAL = auto()
    TYPE_VELOCITY_XY = auto()
    TYPE_VELOCITY_Z = auto()
    TYPE_WIND_DIRECTION = auto()
    TYPE_WIND_VELOCITY = auto()
    TYPE_YAW_DAMPING_MOMENT_COEFF = auto()
    TYPE_YAW_MOMENT_COEFF = auto()
    TYPE_YAW_RATE = auto()


class FlightEvent(Enum):
    ALTITUDE = auto()
    APOGEE = auto()
    BURNOUT = auto()
    EJECTION_CHARGE = auto()
    EXCEPTION = auto()
    GROUND_HIT = auto()
    IGNITION = auto()
    LAUNCH = auto()
    LAUNCHROD = auto()
    LIFTOFF = auto()
    RECOVERY_DEVICE_DEPLOYMENT = auto()
    SIMULATION_END = auto()
    SIM_ABORT = auto()
    SIM_WARN = auto()
    STAGE_SEPARATION = auto()
    TUMBLE = auto()
