"""Generates a version profile from an OpenRocket jar.

Usage: uv run python tools/generate_profile.py <jar_path> [output_dir]

Starts a JVM for the jar (one jar per process — JPype cannot restart a JVM),
reflects the constants and members orlab relies on, verifies the contract
manifest, and writes src/orlab/profiles/or_XX_XX.py. Regeneration from the
same jar is byte-identical. Exits nonzero without writing if any manifest
member is missing.
"""

import hashlib
import os
import sys

import jpype

from orlab.core.openrocket_instance import OpenRocketInstance, reflect_live_constants
from orlab.core.version import parse_version

HEADER = '''"""OpenRocket {version_string} profile. Generated by tools/generate_profile.py; do not edit.

jar: {jar_name}
sha256: {sha256}
"""

VERSION = {version!r}
VERSION_STRING = "{version_string}"
CORE_ROOT = "{core_root}"
SWING_ROOT = "{swing_root}"
STARTUP = "{startup}"
'''


def _sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _get_class(root_pkg, dotted):
    """Returns the JClass at a dotted path below root_pkg, or None."""
    obj = root_pkg
    for part in dotted.split("."):
        obj = getattr(obj, part, None)
        if obj is None:
            return None
    return obj if isinstance(obj, jpype.JClass) else None


def _has_method(jcls, name):
    return any(str(m.getName()) == name for m in jcls.class_.getMethods())


def _has_private_field(jcls, name):
    return any(str(f.getName()) == name for f in jcls.class_.getDeclaredFields())


def _has_file_constructor(jcls):
    File = jpype.JClass("java.io.File")
    for c in jcls.class_.getConstructors():
        params = list(c.getParameterTypes())
        if len(params) == 1 and params[0] == File.class_:
            return True
    return False


def verify_manifest(instance, startup):
    """Checks every class/member orlab touches at runtime; returns the missing ones."""
    core = instance.openrocket
    swing = instance.openrocket_swing
    missing = []

    def require_class(root, dotted, member_check=None, member_label=None):
        jcls = _get_class(root, dotted)
        if jcls is None:
            if dotted not in missing:
                missing.append(dotted)
        elif member_check is not None and not member_check(jcls):
            missing.append(member_label)
        return jcls

    require_class(
        core, "file.GeneralRocketLoader", _has_file_constructor, "GeneralRocketLoader(File)"
    )
    require_class(
        core, "file.GeneralRocketSaver", lambda c: _has_method(c, "save"), "GeneralRocketSaver.save"
    )
    require_class(
        core,
        "simulation.SimulationOptions",
        lambda c: _has_method(c, "randomizeSeed"),
        "SimulationOptions.randomizeSeed",
    )
    # the declarative contract: every whitelisted setter/getter pair plus
    # the seed accessors (orlab.parallel.DECLARATIVE_KEYS)
    from orlab.parallel import DECLARATIVE_KEYS

    options_members = ["setRandomSeed", "getRandomSeed"]
    for spec in DECLARATIVE_KEYS.values():
        options_members.extend([spec.setter, spec.getter])
    for member in options_members:
        require_class(
            core,
            "simulation.SimulationOptions",
            lambda c, m=member: _has_method(c, m),
            f"SimulationOptions.{member}",
        )
    for listener in (
        "SimulationListener",
        "SimulationEventListener",
        "SimulationComputationListener",
        "AbstractSimulationListener",
    ):
        require_class(core, f"simulation.listeners.{listener}")
    require_class(core, "plugin.PluginModule")

    # get_summary surface: the FlightData scalar getters (getOptimumDelay is
    # 23.09+), the warning set, and the branch accessors (getBranchName
    # through 23.09, getName from 24.12)
    summary_getters = [
        "getBranchCount",
        "getBranch",
        "getWarningSet",
        "getMaxAltitude",
        "getMaxVelocity",
        "getMaxAcceleration",
        "getMaxMachNumber",
        "getTimeToApogee",
        "getFlightTime",
        "getGroundHitVelocity",
        "getLaunchRodVelocity",
        "getDeploymentVelocity",
    ]
    if parse_version(instance.or_version) >= (23, 9):
        summary_getters.append("getOptimumDelay")
    for getter in summary_getters:
        require_class(
            core,
            "simulation.FlightData",
            lambda c, g=getter: _has_method(c, g),
            f"FlightData.{getter}",
        )
    # event types the summary windows anchor on
    _, live_events = reflect_live_constants(core)
    for event in ("LAUNCHROD", "APOGEE", "RECOVERY_DEVICE_DEPLOYMENT", "GROUND_HIT"):
        if event not in live_events:
            missing.append(f"FlightEvent.Type.{event}")

    branch_name_accessor = (
        "getName" if parse_version(instance.or_version) >= (24, 12) else "getBranchName"
    )
    for member in ("get", "getEvents", branch_name_accessor):
        require_class(
            core,
            "simulation.FlightDataBranch",
            lambda c, m=member: _has_method(c, m),
            f"FlightDataBranch.{member}",
        )
    # motor-swap surface: the era-specific MotorConfiguration accessor, the
    # uniform config API, the database entry point, and the file loader
    modern_motors = parse_version(instance.or_version) >= (22, 2)
    mount_accessor = "getMotorConfig" if modern_motors else "getMotorConfiguration"
    require_class(
        core,
        "rocketcomponent.MotorMount",
        lambda c, m=mount_accessor: _has_method(c, m),
        f"MotorMount.{mount_accessor}",
    )
    # MotorConfiguration moved packages after 15.03 (rocketcomponent -> motor)
    config_class = (
        "motor.MotorConfiguration" if modern_motors else "rocketcomponent.MotorConfiguration"
    )
    for member in ("getMotor", "setMotor", "getEjectionDelay", "setEjectionDelay"):
        require_class(
            core,
            config_class,
            lambda c, m=member: _has_method(c, m),
            f"MotorConfiguration.{member}",
        )
    require_class(
        core,
        "startup.Application",
        lambda c: _has_method(c, "getMotorSetDatabase"),
        "Application.getMotorSetDatabase",
    )
    require_class(core, "file.motor.GeneralMotorLoader")
    if modern_motors:
        require_class(
            core,
            "motor.ThrustCurveMotor.Builder",
            lambda c: _has_method(c, "build"),
            "ThrustCurveMotor.Builder.build",
        )

    if startup == "core":
        require_class(
            core,
            "startup.OpenRocketCore",
            lambda c: _has_method(c, "initialize"),
            "OpenRocketCore.initialize",
        )
    else:
        require_class(
            core,
            "startup.Application",
            lambda c: _has_method(c, "setInjector"),
            "Application.setInjector",
        )
        gui_module = require_class(
            swing,
            "startup.GuiModule",
            lambda c: _has_method(c, "startLoader"),
            "GuiModule.startLoader",
        )
        if gui_module is not None:
            for field in ("presetLoader", "motorLoader"):
                if not _has_private_field(gui_module, field):
                    missing.append(f"GuiModule.{field}")

    return missing


def render_profile(
    version_string, jar_name, sha256, core_root, swing_root, startup, data_types, events
):
    """Renders a profile module. Pure and deterministic: same facts, same bytes."""
    body = HEADER.format(
        version_string=version_string,
        jar_name=jar_name,
        sha256=sha256,
        version=parse_version(version_string),
        core_root=core_root,
        swing_root=swing_root,
        startup=startup,
    )
    body += "FLIGHT_DATA_TYPES = (\n"
    body += "".join(f'    "{n}",\n' for n in sorted(data_types))
    body += ")\nFLIGHT_EVENTS = (\n"
    body += "".join(f'    "{n}",\n' for n in sorted(events))
    body += ")\n"
    return body


def main():
    if len(sys.argv) < 2:
        print(__doc__.strip())
        return 2
    jar_path = sys.argv[1]
    out_dir = sys.argv[2] if len(sys.argv) > 2 else "src/orlab/profiles"

    with OpenRocketInstance(jar_path=jar_path) as instance:
        version_string = instance.or_version
        data_types, events = reflect_live_constants(instance.openrocket)
        startup = "core" if _get_class(instance.openrocket, "startup.OpenRocketCore") else "gui"
        missing = verify_manifest(instance, startup)
        # The roots the just-completed startup actually verified against this jar.
        roots = (instance.profile.core_root, instance.profile.swing_root)

    if missing:
        print(f"MANIFEST FAILURE for {version_string}: missing {', '.join(missing)}")
        return 1

    body = render_profile(
        version_string,
        os.path.basename(jar_path),
        _sha256(jar_path),
        roots[0],
        roots[1],
        startup,
        data_types,
        events,
    )
    version = parse_version(version_string)
    out_path = os.path.join(out_dir, f"or_{version[0]:02d}_{version[1]:02d}.py")
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(body)
    print(f"WROTE {out_path}: {len(data_types)} data types, {len(events)} events, {startup=}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
