"""Regenerates src/orlab/_enums.py from the checked-in version profiles.

Usage: uv run python tools/generate_enums.py

FlightDataType and FlightEvent become the union of constants across all
profiles (a static import surface; per-version availability is enforced at
translation time). Run after generating a new profile; output is deterministic.
"""

import sys

from orlab.profiles import profiles

HEADER = '''"""Public enums. FlightDataType and FlightEvent are generated by
tools/generate_enums.py as the union of constants across all version profiles;
availability on the loaded OpenRocket version is enforced when translating.
Do not edit them by hand — regenerate instead."""

from enum import Enum, auto

__all__ = [
    "OrLogLevel",
    "FlightDataType",
    "FlightEvent",
]


class OrLogLevel(Enum):
    OFF = auto()
    ERROR = auto()
    WARN = auto()
    INFO = auto()
    DEBUG = auto()
    TRACE = auto()
    ALL = auto()
'''


def render_enums():
    """Renders _enums.py from the profile registry. Pure and deterministic."""
    data_types = sorted(set().union(*(p.flight_data_types for p in profiles.values())))
    events = sorted(set().union(*(p.flight_events for p in profiles.values())))

    body = HEADER
    body += "\n\nclass FlightDataType(Enum):\n"
    body += "".join(f"    {n} = auto()\n" for n in data_types)
    body += "\n\nclass FlightEvent(Enum):\n"
    body += "".join(f"    {n} = auto()\n" for n in events)
    return body


def main():
    with open("src/orlab/_enums.py", "w") as fh:
        fh.write(render_enums())
    types = set().union(*(p.flight_data_types for p in profiles.values()))
    events = set().union(*(p.flight_events for p in profiles.values()))
    print(f"WROTE src/orlab/_enums.py: {len(types)} data types, {len(events)} events")
    return 0


if __name__ == "__main__":
    sys.exit(main())
