"""Generates a version profile from an OpenRocket jar.

Usage: uv run python tools/generate_profile.py <jar_path> [output_dir]

Starts a JVM for the jar (one jar per process — JPype cannot restart a JVM),
reflects the constants and members orlab relies on, verifies the contract
manifest, and writes src/orlab/profiles/or_XX_XX.py. Regeneration from the
same jar is byte-identical. Exits nonzero without writing if any manifest
member is missing.
"""

import hashlib
import os
import sys

import jpype

from orlab.core.openrocket_instance import OpenRocketInstance
from orlab.core.version import parse_version, select_roots

HEADER = '''"""OpenRocket {version_string} profile. Generated by tools/generate_profile.py; do not edit.

jar: {jar_name}
sha256: {sha256}
"""

VERSION = {version!r}
VERSION_STRING = "{version_string}"
CORE_ROOT = "{core_root}"
SWING_ROOT = "{swing_root}"
STARTUP = "{startup}"
'''


def _sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _has_class(root_pkg, dotted):
    obj = root_pkg
    for part in dotted.split("."):
        obj = getattr(obj, part, None)
        if obj is None:
            return False
    return isinstance(obj, jpype.JClass)


def _has_method(jcls, name):
    return any(str(m.getName()) == name for m in jcls.class_.getMethods())


def _has_private_field(jcls, name):
    return any(str(f.getName()) == name for f in jcls.class_.getDeclaredFields())


def _has_file_constructor(jcls):
    File = jpype.JClass("java.io.File")
    for c in jcls.class_.getConstructors():
        params = list(c.getParameterTypes())
        if len(params) == 1 and params[0] == File.class_:
            return True
    return False


def reflect(instance):
    core = instance.openrocket
    swing = instance.openrocket_swing

    fdt_cls = core.simulation.FlightDataType
    data_types = sorted(
        str(f.getName())
        for f in fdt_cls.class_.getDeclaredFields()
        if f.getType() == fdt_cls.class_
    )
    events = sorted(str(v.name()) for v in core.simulation.FlightEvent.Type.values())

    startup = "core" if _has_class(core, "startup.OpenRocketCore") else "gui"

    # Contract manifest: everything orlab touches at runtime must exist.
    missing = []

    def require(ok, what):
        if not ok:
            missing.append(what)

    require(_has_file_constructor(core.file.GeneralRocketLoader), "GeneralRocketLoader(File)")
    require(_has_method(core.file.GeneralRocketSaver, "save"), "GeneralRocketSaver.save")
    require(
        _has_method(core.simulation.SimulationOptions, "randomizeSeed"),
        "SimulationOptions.randomizeSeed",
    )
    for listener in (
        "SimulationListener",
        "SimulationEventListener",
        "SimulationComputationListener",
        "AbstractSimulationListener",
    ):
        require(_has_class(core, f"simulation.listeners.{listener}"), f"listeners.{listener}")
    require(_has_method(core.startup.Application, "setInjector"), "Application.setInjector")
    require(_has_class(core, "plugin.PluginModule"), "plugin.PluginModule")
    if startup == "core":
        require(_has_method(core.startup.OpenRocketCore, "initialize"), "OpenRocketCore.initialize")
    else:
        gui_module = swing.startup.GuiModule
        require(isinstance(gui_module, jpype.JClass), "startup.GuiModule")
        require(_has_method(gui_module, "startLoader"), "GuiModule.startLoader")
        for field in ("presetLoader", "motorLoader"):
            require(_has_private_field(gui_module, field), f"GuiModule.{field}")

    return data_types, events, startup, missing


def main():
    jar_path = sys.argv[1]
    out_dir = sys.argv[2] if len(sys.argv) > 2 else "src/orlab/profiles"

    with OpenRocketInstance(jar_path=jar_path) as instance:
        version_string = instance.or_version
        version = parse_version(version_string)
        data_types, events, startup, missing = reflect(instance)
        roots = select_roots(version_string)

    if missing:
        print(f"MANIFEST FAILURE for {version_string}: missing {', '.join(missing)}")
        return 1

    body = HEADER.format(
        version_string=version_string,
        jar_name=os.path.basename(jar_path),
        sha256=_sha256(jar_path),
        version=version,
        core_root=roots.core,
        swing_root=roots.swing,
        startup=startup,
    )
    body += "FLIGHT_DATA_TYPES = (\n"
    body += "".join(f'    "{n}",\n' for n in data_types)
    body += ")\nFLIGHT_EVENTS = (\n"
    body += "".join(f'    "{n}",\n' for n in events)
    body += ")\n"

    out_path = os.path.join(out_dir, f"or_{version[0]:02d}_{version[1]:02d}.py")
    with open(out_path, "w") as fh:
        fh.write(body)
    print(f"WROTE {out_path}: {len(data_types)} data types, {len(events)} events, {startup=}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
